name: $(Build.BuildID)

trigger:
- master

resources:
- repo: self

variables:
  Folder: 'dist'
  TEAM_CIBUILD: 'true'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: macOS_Linux_Phase
    displayName: 'Build'
    strategy:
      matrix:
        macOS:
          OS: 'macOS'
          vmImageName: 'macOS-latest'
        Linux:
          OS: 'Linux'
          vmImageName: 'ubuntu-latest'
      maxParallel: 2
    pool:
      vmImage: $(vmImageName)
    steps:
    - template: build/unitTests.yml
      parameters:
        os: '$(OS)'
        workingDirectory: '$(System.DefaultWorkingDirectory)/src/BerService.Pwsh'

  - job: Windows_Phase
    displayName: Build Windows
    pool:
      vmImage: 'windows-latest'

    steps:
    - template: build/unitTests.yml
      parameters:
        os: 'Windows'
        buildHelp: 'true'
        workingDirectory: '$(System.DefaultWorkingDirectory)/src/BerService.Pwsh'
        options: '-buildHelp -analyzeScript -runTests -codeCoverage'

    - task: CopyFiles@2
      displayName: 'Copy Module to Artifacts Folder'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/src/BerService.Pwsh'
        Contents: |
          README.md
          .gitignore
          dist\**
        TargetFolder: '$(build.artifactstagingdirectory)/module'
      condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Module'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/module'
        artifact: 'module'
      condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

    - task: CopyFiles@2
      displayName: 'Copy Integration Tests Artifacts Folder'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/src/BerService.Pwsh'
        Contents: |
          dist\*.psd1
          integration\**
        TargetFolder: '$(build.artifactstagingdirectory)/Tests'
      condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Tests'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/Tests'
        artifact: 'test'
      condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

- stage: Package
  displayName: Package Management
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Package Management
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'Default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: NuGetToolInstaller@0
            displayName: 'Install NuGet 5.2.0'
            inputs:
              versionSpec: 5.2.0
              
          - task: PowerShell@2
            displayName: 'Install Module Dependencies'
            inputs:
              targetType: 'inline'
              script: |
                # Load the psd1 file so you can read the required modules and install them
                $manifest = Import-PowerShellDataFile .\$(Folder)\*.psd1

                # Install each module
                if ($manifest.RequiredModules) {
                  $manifest.RequiredModules | ForEach-Object { Install-Module -Name $_ -Repository PSGallery -F -Scope CurrentUser }
                }
              workingDirectory: '$(Pipeline.Workspace)/module'

          - task: PowerShell@2
            displayName: 'Compute Version Number'
            inputs:
              targetType: 'inline'
              script: |
                # Load the psd1 file so you can read the version
                $manifest = Import-PowerShellDataFile .\$(Folder)\*.psd1

                Write-Host "##vso[task.setvariable variable=PACKAGE_VERSION;isOutput=false]$($manifest.ModuleVersion).$(Build.BuildId)"
              workingDirectory: '$(Pipeline.Workspace)/module'

          - task: PowerShell@2
            displayName: 'Create NuSpec from PSD1'
            inputs:
              targetType: 'inline'
              script: |
                Install-Module -Name Trackyon.Nuget -Scope CurrentUser -Force -Verbose
                ConvertTo-NuSpec -Path ./$(Folder)/Trackyon.Ber.psd1
              workingDirectory: '$(Pipeline.Workspace)/module'

          - task: NuGetCommand@2
            displayName: 'Pack Module'
            inputs:
              command: pack
              packagesToPack: '$(Pipeline.Workspace)/module/$(Folder)/Trackyon.Ber.nuspec'
              packDestination: '$(Pipeline.Workspace)/module/$(Folder)'
              versioningScheme: byEnvVar
              versionEnvVar: 'PACKAGE_VERSION'

          - task: NuGetCommand@2
            displayName: 'Push Module'
            inputs:
              command: 'push'
              packagesToPush: '$(Pipeline.Workspace)/module/$(Folder)/*.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: 'ber'
              allowPackageConflicts: true

- stage: Testing
  displayName: Testing stage
  dependsOn: Package
  jobs:
  
  - template: build/integrationTests.yml
    parameters:
      displayName: 'Linux'
      os: 'Linux'
      name: 'Linux'
      pool: 'ubuntu-latest'

  - template: build/integrationTests.yml
    parameters:
      displayName: 'Windows'
      os: 'Windows'
      name: 'Windows'
      pool: 'windows-latest'

  - template: build/integrationTests.yml
    parameters:
      displayName: 'macOS'
      os: 'macOS'
      pool: 'macOS-latest'
      name: 'macOS'

- stage: Produciton
  displayName: PowerShell Gallery
  dependsOn: Testing
  jobs:
  - deployment: Deploy
    displayName: PowerShell Gallery
    pool:
      vmImage: 'windows-latest'
    environment: 'PowerShell Gallery'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: NuGetToolInstaller@0
            displayName: 'Install NuGet 5.2.0'
            inputs:
              versionSpec: 5.2.0

          - task: PowerShell@2
            displayName: 'Install Module Dependencies'
            inputs:
              targetType: 'inline'
              script: |
                # Load the psd1 file so you can read the required modules and install them
                $manifest = Import-PowerShellDataFile .\$(Folder)\*.psd1

                # Install each module
                if ($manifest.RequiredModules) {
                  $manifest.RequiredModules | ForEach-Object { Install-Module -Name $_ -Repository PSGallery -F -Scope CurrentUser }
                }
              workingDirectory: '$(Pipeline.Workspace)/module'

          - task: PowerShell@2
            displayName: 'Create NuSpec from PSD1'
            inputs:
              targetType: 'inline'
              script: |
                Install-Module -Name Trackyon.Nuget -Scope CurrentUser -Force -Verbose
                ConvertTo-NuSpec -Path ./$(Folder)/Trackyon.Ber.psd1
              workingDirectory: '$(Pipeline.Workspace)/module'

          - task: NuGetCommand@2
            displayName: 'Pack Module'
            inputs:
              command: pack
              packagesToPack: '$(Pipeline.Workspace)/module/$(Folder)/Trackyon.Ber.nuspec'
              packDestination: '$(Pipeline.Workspace)/module/$(Folder)'

          - task: NuGetCommand@2
            displayName: 'Push Module'
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/module/$(Folder)/*.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: 'PowerShell Gallery'
